<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { apiRequest } from '../api/client'
interface Taxonomy { id: number; name: string; slug: string }
const categories = ref<Taxonomy[]>([]); const tags = ref<Taxonomy[]>([]); const name = ref(''); const slug = ref(''); const kind = ref<'categories'|'tags'>('categories'); const errorMessage = ref('')
async function load(): Promise<void> { try { [categories.value, tags.value] = await Promise.all([apiRequest<{categories:Taxonomy[]}>('/api/admin/categories').then(x=>x.categories),apiRequest<{tags:Taxonomy[]}>('/api/admin/tags').then(x=>x.tags)]) } catch (error) { errorMessage.value = error instanceof Error ? error.message : 'Unable to load taxonomy.' } }
async function create(): Promise<void> { try { const response = await apiRequest<Record<string, Taxonomy>>(`/api/admin/${kind.value}`, { method:'POST', body:{name:name.value,slug:slug.value} }); const item=response[kind.value === 'categories' ? 'category' : 'tag']; (kind.value === 'categories' ? categories : tags).value.push(item); name.value='';slug.value='' } catch(error) { errorMessage.value=error instanceof Error?error.message:'Unable to save taxonomy.' } }
onMounted(load)
</script>
<template><section class="taxonomy-view"><p class="eyebrow">Organization</p><h1>Categories &amp; tags</h1><form class="taxonomy-form" @submit.prevent="create"><label>Type <select v-model="kind"><option value="categories">Category</option><option value="tags">Tag</option></select></label><label>Name <input v-model="name" required /></label><label>Slug <input v-model="slug" required pattern="[a-z0-9-]+" /></label><button class="primary-button">Add</button></form><p v-if="errorMessage" role="alert" class="form-error">{{errorMessage}}</p><div class="lists"><section><h2>Categories</h2><p v-for="item in categories" :key="item.id">{{item.name}} <small>/{{item.slug}}</small></p></section><section><h2>Tags</h2><p v-for="item in tags" :key="item.id">{{item.name}} <small>/{{item.slug}}</small></p></section></div></section></template>
<style scoped>h1{margin:0 0 20px;font-size:28px}.taxonomy-form{display:flex;gap:12px;align-items:end;flex-wrap:wrap;border-bottom:1px solid #d9dfdb;padding-bottom:16px}label{display:grid;gap:6px;font-size:13px;font-weight:650}input,select{min-height:40px;border:1px solid #b9c5be;border-radius:3px;padding:0 10px;font:inherit}.lists{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:32px;padding-top:18px}h2{font-size:17px}small{color:#68756d}@media(max-width:600px){.lists{grid-template-columns:1fr}}</style>
